CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id SERIAL PRIMARY KEY,
    service_name VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
);

INSERT INTO users (name, email) VALUES ('Alice Johnson', 'alice.johnson@example.com');
INSERT INTO users (name, email) VALUES ('Bob Smith', 'bob.smith@example.com');
INSERT INTO users (name, email) VALUES ('Carol Williams', 'carol.williams@example.com');
INSERT INTO users (name, email) VALUES ('David Brown', 'david.brown@example.com');
INSERT INTO users (name, email) VALUES ('Emma Jones', 'emma.jones@example.com');
INSERT INTO users (name, email) VALUES ('Frank Garcia', 'frank.garcia@example.com');
INSERT INTO users (name, email) VALUES ('Grace Miller', 'grace.miller@example.com');
INSERT INTO users (name, email) VALUES ('Henry Davis', 'henry.davis@example.com');
INSERT INTO users (name, email) VALUES ('Isabella Rodriguez', 'isabella.rodriguez@example.com');
INSERT INTO users (name, email) VALUES ('Jack Martinez', 'jack.martinez@example.com');
INSERT INTO users (name, email) VALUES ('Karen Hernandez', 'karen.hernandez@example.com');
INSERT INTO users (name, email) VALUES ('Leo Lopez', 'leo.lopez@example.com');
INSERT INTO users (name, email) VALUES ('Mia Gonzalez', 'mia.gonzalez@example.com');
INSERT INTO users (name, email) VALUES ('Noah Wilson', 'noah.wilson@example.com');
INSERT INTO users (name, email) VALUES ('Olivia Anderson', 'olivia.anderson@example.com');
INSERT INTO users (name, email) VALUES ('Paul Thomas', 'paul.thomas@example.com');
INSERT INTO users (name, email) VALUES ('Quinn Taylor', 'quinn.taylor@example.com');
INSERT INTO users (name, email) VALUES ('Rachel Moore', 'rachel.moore@example.com');
INSERT INTO users (name, email) VALUES ('Samuel Jackson', 'samuel.jackson@example.com');
INSERT INTO users (name, email) VALUES ('Tina Martin', 'tina.martin@example.com');
INSERT INTO users (name, email) VALUES ('Uma Thompson', 'uma.thompson@example.com');
INSERT INTO users (name, email) VALUES ('Victor White', 'victor.white@example.com');
INSERT INTO users (name, email) VALUES ('Wendy Harris', 'wendy.harris@example.com');
INSERT INTO users (name, email) VALUES ('Xavier Clark', 'xavier.clark@example.com');
INSERT INTO users (name, email) VALUES ('Yvonne Lewis', 'yvonne.lewis@example.com');
INSERT INTO users (name, email) VALUES ('Zachary Walker', 'zachary.walker@example.com');
INSERT INTO users (name, email) VALUES ('Abigail Hall', 'abigail.hall@example.com');
INSERT INTO users (name, email) VALUES ('Benjamin Allen', 'benjamin.allen@example.com');
INSERT INTO users (name, email) VALUES ('Chloe Young', 'chloe.young@example.com');
INSERT INTO users (name, email) VALUES ('Daniel King', 'daniel.king@example.com');
INSERT INTO users (name, email) VALUES ('Ella Wright', 'ella.wright@example.com');
INSERT INTO users (name, email) VALUES ('Felix Scott', 'felix.scott@example.com');
INSERT INTO users (name, email) VALUES ('Gabriella Green', 'gabriella.green@example.com');
INSERT INTO users (name, email) VALUES ('Henry Adams', 'henry.adams@example.com');
INSERT INTO users (name, email) VALUES ('Iris Baker', 'iris.baker@example.com');
INSERT INTO users (name, email) VALUES ('Jason Nelson', 'jason.nelson@example.com');
INSERT INTO users (name, email) VALUES ('Katherine Carter', 'katherine.carter@example.com');
INSERT INTO users (name, email) VALUES ('Liam Mitchell', 'liam.mitchell@example.com');
INSERT INTO users (name, email) VALUES ('Megan Perez', 'megan.perez@example.com');
INSERT INTO users (name, email) VALUES ('Nathan Roberts', 'nathan.roberts@example.com');
INSERT INTO users (name, email) VALUES ('Olivia Turner', 'olivia.turner@example.com');
INSERT INTO users (name, email) VALUES ('Patrick Phillips', 'patrick.phillips@example.com');
INSERT INTO users (name, email) VALUES ('Queenie Campbell', 'queenie.campbell@example.com');
INSERT INTO users (name, email) VALUES ('Robert Parker', 'robert.parker@example.com');
INSERT INTO users (name, email) VALUES ('Sophia Evans', 'sophia.evans@example.com');
INSERT INTO users (name, email) VALUES ('Thomas Edwards', 'thomas.edwards@example.com');
INSERT INTO users (name, email) VALUES ('Ursula Collins', 'ursula.collins@example.com');
INSERT INTO users (name, email) VALUES ('Vincent Stewart', 'vincent.stewart@example.com');
INSERT INTO users (name, email) VALUES ('Victoria Sanchez', 'victoria.sanchez@example.com');
INSERT INTO users (name, email) VALUES ('William Morris', 'william.morris@example.com');

INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 1);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 1);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 1);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 1);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 1);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 1);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 2);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 2);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 2);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 2);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 2);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 3);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 4);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 5);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 5);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 5);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 5);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 5);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 6);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 6);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 6);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 6);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 6);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 7);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 8);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 9);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 9);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 9);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 9);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 9);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 10);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 11);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 11);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 11);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 11);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 11);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 12);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 12);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 12);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 12);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 12);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 13);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 13);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 13);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 13);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 13);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 13);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 14);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 14);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 15);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 15);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 16);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 16);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 16);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 16);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 17);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 17);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 17);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 18);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 18);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 18);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 18);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 18);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 18);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 19);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 19);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 19);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 19);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 20);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 20);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 20);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 21);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 22);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 22);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 22);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 22);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 22);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 23);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 23);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 23);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 23);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 23);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 23);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 24);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 24);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 24);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 25);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 25);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 25);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 25);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 26);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 26);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 26);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 26);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 26);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 26);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 27);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 27);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 27);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 28);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 28);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 28);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 28);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 28);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 28);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 29);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 29);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 29);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 29);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 30);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 30);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 30);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 30);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 30);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 31);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 31);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 31);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 31);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 32);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 33);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 33);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 33);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 33);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 33);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 34);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 34);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 34);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 35);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 36);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 36);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 36);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 37);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 37);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 37);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 37);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 37);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 37);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 38);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 38);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 39);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 39);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 39);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 40);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 40);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 40);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 40);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 40);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 40);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 41);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 42);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 42);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 42);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 42);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 42);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 42);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 43);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 43);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 43);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 43);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 43);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 44);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 44);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 44);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 44);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 44);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 45);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 45);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Netflix', 45);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 46);
INSERT INTO subscriptions (service_name, user_id) VALUES ('VK Музыка', 46);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 46);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 46);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 47);
INSERT INTO subscriptions (service_name, user_id) VALUES ('HBO Max', 47);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 47);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 47);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Storytel', 47);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple Music', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Disney+', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Xbox Game Pass', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 48);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Spotify', 49);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Scribd', 49);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 49);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Apple TV+', 49);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Amazon Prime Video', 49);
INSERT INTO subscriptions (service_name, user_id) VALUES ('PlayStation Plus', 49);
INSERT INTO subscriptions (service_name, user_id) VALUES ('EA Play', 50);
INSERT INTO subscriptions (service_name, user_id) VALUES ('Яндекс.Плюс', 50);
